version: '3'
services:
  app:
    build: .
    ports:
    - "80:8080"
    depends_on:
      - database
    expose:
      - "8080"
  database:
    image: "mongo"
    ports:
    - "27017:27017"
    expose:
    - "27017"
